# Site settings
title: Badarinath L R
twitter_username: Badarikashyap
name: Badarinath L R

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Blog
   url: https://github.com/badarilr
 - title: Linkedin
   url: https://www.linkedin.com/in/badarinathlr/
 

#Any buzzword skills you want to include
skills:
 - Manual Testing
 - Mobile Testing
 - Automation
 - Selenium
 - Product management
 - API Testing
 - Java
 - SQL
 - REST
 - No Code Tools
 

#Work experience is required
roles:
- title: QA Manager
   start: 2022
   end: 2024
   employer: Shell Markest India
   description: •	Supervised a quality team of 40+ members across four departments, Workday, ADF, IMS & Shell Health bolstering departmental integration of processes and took ownership of end to end Testing </a>
 - title: Test Lead
   start: 2012
   end: 2021
   employer: Evry India
   description: Develop and execute test plans and tracking and reporting on key metrics for customer adoption and success. Products include <a href="https://www.dooap.com" taget="_blank">Dooap</a>, <a href="https://www.beyondtrust.com/" taget="_blank">BeyondTrust</a>
 - title: Senior Test Engineer
   start: 2010
   end: 2012
   employer: Mindtree Ltd
   description: Contributed to Southewest Rapid rewards project as test engineer.Performed System Testing, Functional Testing, Automation Testing,GUI Testing, Regression Testing, Ad hoc Testing, Migration and database testing
 - title: Software Engineer
   start: 2006
   end: 2010
   employer: Wipro Technologies
   description: Worked as a Software Engineer in the Regression, Performance, Exploratory and Localization testing for HP Multifunctional Pheripherals. Design and Execution of FQP’s (Feature Qualification Plan) and high priority Test scripts and review based on the respective documents and comments which are attached in the design templates
 

#Education is required
education:
 - level: Master of Computer Applications (M.C.A)
   date: 2006
   University: Visvesvaraya Technological University


intro: |
 Knowledgeable and performance-driven Test Lead with experience in overall 12+ years in in software design and testing of Web, Content Management System,Power Apps, MFP, Identity Access Management and Mobile applications. Proven ability in all facets of quality control such as test planning, functional testing, regression testing and user acceptance testing.
    • Passion for testing, assuring end-to-end quality in development cycle
    • Customer and business oriented
    • Excellent leadership, technical and trouble-shooting skills
    • Expertise in Invoice Processing , Health Care , Device Management & Travel Domain
    • Change management adapting to newer technologies
    • Experience in working under Agile development teams (Scrum )
    • Worked as Onsite coordinator for Southwest Airlines in Dallas, TX, USA. & Dooap, Tampere, Finland
    • Ability to work effectively across teams located in different geographies
    
additionalinfo: |

  <strong>Testing Tools Frameworks</strong>: My current role uses C# as the primary language and have been testing applications in C# for the last two years. I am familiar with implementation of Xamarin UI Test framework. I have experience with an array of testing tools and technologies such as Selenium,Postman,Appium,TestNG <br/><br/>
  <strong>CI/CD Control</strong>: I have a good knowledge of application life-cycle management and have worked with Azure DevOps, SVN, Git, Jenkins, TeamCity, etc <br/><br/>
  <strong>Test Management</strong>:  :I have good knowledge of agile and product managemnt , defect life cycle and have worked with Jira, DevOps, HP Quality Center, qTest <br/><br/>
   
  

theme: jekyll-theme-minimal
